on:
  push:
      paths:
          - AArch64/**
      workflow_dispatch:
  pull_request:
      paths:
          - AArch64/**

defaults:
  run:
    working-directory: ./AArch64

jobs:
    replace:
      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{github.event.pull_request.head.ref}}
        - name: Replace 'arm' with 'aarch64'
          run: sed -i 's|arm|aarch64|g' './Makefile'
          # For comments
        - name: Replace 'gnueabihf-' with 'gnu-'
          run: sed -i 's|gnueabihf-|gnu-|g' './Makefile'
        - name: Commit and push
          run: |
            if [ -n "$(git status --porcelain)" ]; then # Check if it has changes.
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add './Makefile'
              git commit -m 'Fix typos'
              git push origin
            fi

    build:
        needs: replace
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Install gcc-aarch64-linux-gnu
              run: sudo apt install gcc-aarch64-linux-gnu --yes
            - name: Build all AArch64 programs
              run: |
                    make \
                    AS=aarch64-linux-gnu-as \
                    LD=aarch64-linux-gnu-ld \
                    CC=aarch64-linux-gnu-gcc \
                    CL=aarch64-linux-gnu-gcc \
                    all
            - name: Clean all
              run: make cleanall
