on:
  push:
      paths:
          - AArch64/**
      branches-ignore:
        - issue-templates
      workflow-dispatch:
  pull_request:
      paths:
          - AArch64/**
      branches-ignore:
        - issue-templates

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Install gcc-aarch64-linux-gnu
              run: sudo apt install gcc-aarch64-linux-gnu
            - uses: actions/checkout@v2
            - name: Build all AArch64 programs
              working-directory: ./AArch64
              run: |
                    make \
                    AS=aarch64-linux-gnu-as \
                    LD=aarch64-linux-gnu-ld \
                    CC=aarch64-linux-gnu-gcc \
                    CL=aarch64-linux-gnu-gcc \
                    all
            - name: Clean all
              working-directory: ./AArch64
              run: |
                    make cleanall
