on:
  push:
      paths:
          - ARM/**
      workflow_dispatch:
  pull_request:
      paths:
          - ARM/**

defaults:
  run:
    working-directory: ./ARM

jobs:
    replace:
      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{github.event.pull_request.head.ref}}
        - name: Replace 'aarch64' with 'arm'
          run: sed -i 's|aarch64|arm|g' './Makefile'
          # For comments
        - name: Replace 'gnu-' with 'gnueabihf-'
          run: sed -i 's|gnu-|-gnueabihf-|g' './Makefile'
        - name: Commit and push
          run: |
            if [ -n "$(git status --porcelain)" ]; then # Check if it has changes.
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add './Makefile'
              git commit -m 'Fix typos'
              git push origin
            fi

    build:
        needs: replace
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Install binutils-arm-linux-gnueabihf
              run: sudo apt install binutils-arm-linux-gnueabihf --yes
            - name: Build all ARM programs
              run: |
                    make \
                    AS=arm-linux-gnueabihf-as \
                    LD=arm-linux-gnueabihf-ld \
                    all
            - name: Clean all
              run: make cleanall
