on: push

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Install GNU Arm Embedded Toolchain
              uses: marvinschopf/install-gcc-arm-none-eabi@main
            - name: Run makefile
              run: |
                    make \
                    AS=arm-none-eabi-as \
                    LD=arm-none-eabi-ld \
                    all
