on:
  push:
      paths:
          - src/**
          - Makefile
      branches-ignore:
        - issue-templates
      workflow-dispatch:
  pull_request:
      paths:
          - src/**
          - Makefile
      branches-ignore:
        - issue-templates

jobs:
    build-arm:
        runs-on: ubuntu-20.04

        steps:
            - name: Install gcc-arm-linux-gnueabihf
              run: sudo apt install gcc-arm-linux-gnueabihf
            - uses: actions/checkout@v2
            - name: Build all ARM programs
              working-directory: ./ARM
              run: |
                    make \
                    AS=arm-linux-gnueabihf-as \
                    LD=arm-linux-gnueabihf-ld \
                    CC=arm-linux-gnueabihf-gcc \
                    CL=arm-linux-gnueabihf-gcc \
                    all
            - name: Clean all
              working-directory: ./ARM
              run: |
                    make cleanall
