on:
  push:
      paths:
          - src/**
  pull_request:
  workflow-dispatch:

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Install gcc-arm-linux-gnueabihf
              run: sudo apt install gcc-arm-linux-gnueabihf
            - uses: actions/checkout@v2
            - name: Build all programs
              run: |
                    make \
                    AS=arm-linux-gnueabihf-as \
                    LD=arm-linux-gnueabihf-ld \
                    CC=arm-linux-gnueabihf-gcc \
                    CL=arm-linux-gnueabihf-gcc \
                    all
            - name: Clean all
              run: |
                    make cleanall
